# --- CENTRALV specific parameters ---
# Independent PPO with value norm, layer_norm, orthogonal, value clip
# but, without death agent mask, data chunk

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "episode_eval"

buffer_size: 32
batch_size_run: 1
batch_size: 32
accumulated_episodes: 4

mac: 'basic_mac'
agent: 'n_rnn'
t_max: 2000000

obs_agent_id: True

lr: 0.0005
critic_coef: 0.5
entropy: 0.01
gae_lambda: 0.95
mini_epochs: 5
eps_clip: 0.2
save_probs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"

use_layer_norm: True
use_orthogonal: True
gain: 0.01
use_value_norm: True
gamma_lr: 0.997 # 0.95, 0.98, 0.999
name: "ippo_env=8_adam_gae"
